/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        surface: '#f1fcf4',
        'surface-dim': '#d1ddd5',
        'surface-bright': '#f1fcf4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#ebf6ee',
        'surface-container': '#e5f1e8',
        'surface-container-high': '#dfebe3',
        'surface-container-highest': '#dae5dd',
        'on-surface': '#141e19',
        'on-surface-variant': '#3e4943',
        'inverse-surface': '#28332d',
        'inverse-on-surface': '#e8f4eb',
        outline: '#6e7a73',
        'outline-variant': '#bec9c1',
        'surface-tint': '#006c4c',
        primary: '#005f43',
        'on-primary': '#ffffff',
        'primary-container': '#167a58',
        'on-primary-container': '#aaffd7',
        'inverse-primary': '#7fd8b0',
        secondary: '#4f625c',
        'on-secondary': '#ffffff',
        'secondary-container': '#d2e7de',
        'on-secondary-container': '#556861',
        tertiary: '#7b4700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9d5c00',
        'on-tertiary-container': '#ffead9',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f1fcf4',
        'on-background': '#141e19',
        'surface-variant': '#dae5dd',
        'primary-fixed': '#9af5cb',
        'primary-fixed-dim': '#7fd8b0',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#005138',
        'secondary-fixed': '#d2e7de',
        'secondary-fixed-dim': '#b7cbc3',
        'on-secondary-fixed': '#0d1f1a',
        'on-secondary-fixed-variant': '#384b44',
        'tertiary-fixed': '#ffdcbd',
        'tertiary-fixed-dim': '#ffb86f',
        'on-tertiary-fixed': '#2c1600',
        'on-tertiary-fixed-variant': '#693c00',
        'pistachio-light': '#f2f7f4',
        mint: '#dff4eb',
        'green-deep': '#005f43',
        'charcoal-muted': '#64716b',
        'paper-warm': '#f7f5ee',
        'border-subtle': '#d9ded8',
        rose: '#b84f5d',
        'status-rose': '#b84f5d',
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        eyebrow: ["12px", { lineHeight: "1", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-bold": ["13px", { lineHeight: "1.2", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "1", fontWeight: "500" }],
        "badge-text": ["11px", { lineHeight: "1", fontWeight: "800" }],
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "20px",
        "margin-mobile": "16px",
      },
      maxWidth: {
        "max-width": "1200px",
      }
    },
  },
  plugins: [],
}
